# Generated by Django 3.0.5 on 2020-04-22 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('MALE', 'Male'),
                                                     ('FEMALE', 'Female'),
                                                     ('UNKNOWN', 'Unknown')],
                                            max_length=7)),
                ('age', models.CharField(blank=True, max_length=64)),
                ('eye_color', models.CharField(max_length=64)),
                ('hair_color', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=128)),
                ('producer', models.CharField(max_length=128)),
                ('release_date', models.PositiveSmallIntegerField(validators=[
                    django.core.validators.MinValueValidator(1985),
                    django.core.validators.MaxValueValidator(2021)])),
                ('rt_score', models.PositiveSmallIntegerField()),
                ('people', models.ManyToManyField(default=None,
                                                  to='gstudio.People')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
